In [139]:
import pandas as pd
import matplotlib.pyplot as plt

In [140]:
# Add styling
plt.style.use(['ggplot'])
px = 1/plt.rcParams['figure.dpi']  # pixel in inches

In [141]:
wta_matches_2015 = pd.read_csv('tennis_wta-master/wta_matches_2015.csv')

In [142]:
def extract_winners(datafr):
    
    # Make a copy of the dataframe
    datafr = datafr.copy()

    # start by creating a hierarchical index by placing Winners ID & Tournament ID on the index
    datafr = datafr.set_index(['winner_id']).sort_index()

    # drop unnessecary columns
    datafr = datafr.drop(['loser_rank', 'loser_rank_points', 'l_ace', 'l_df', 'l_svpt', 'l_1stIn', 'l_1stWon',
    'l_2ndWon', 'l_SvGms', 'l_bpSaved', 'l_bpFaced', 'loser_id','loser_seed', 'loser_entry', 'loser_name',
    'loser_hand', 'loser_ht', 'loser_ioc', 'loser_age'], axis = 1)

    # rename index
    datafr = datafr.rename_axis( index = {'winner_id': 'id'} )

    # print(datafr.columns)

    return datafr

In [143]:
def extract_losers(datafr):
    
    # Make a copy of the dataframe
    datafr = datafr.copy()

    # start by creating a hierarchical index by placing Winners ID & Tournament ID on the index
    datafr = datafr.set_index(['loser_id']).sort_index()

    # drop unnessecary columns
    datafr = datafr.drop(['winner_rank', 'winner_rank_points', 'w_ace', 'w_df', 'w_svpt', 'w_1stIn', 'w_1stWon',
    'w_2ndWon', 'w_SvGms', 'w_bpSaved', 'w_bpFaced', 'winner_id','winner_seed', 'winner_entry', 'winner_name',
    'winner_hand', 'winner_ht', 'winner_ioc', 'winner_age'], axis = 1)

    # # rename
    datafr = datafr.rename_axis( index = {'loser_id': 'id'} )


    return datafr

In [150]:
def combine_players(winners, losers):

    players = pd.concat([winners, losers])

    return players

In [189]:
winners = extract_winners(wta_matches_2015)
losers = extract_losers(wta_matches_2015)

players = combine_players(winners, losers)


players.loc[200033,  : ][['winner_name', 'loser_name']]

            winner_name       loser_name
id
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033  Serena Williams              NaN
200033              NaN  Serena Williams
200033              NaN  Serena Williams
200033              NaN  Serena Williams
200033              NaN  Serena Williams
200033              NaN  Serena Williams
200033              NaN  Serena Williams