In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import os
import warnings
warnings.filterwarnings("ignore")

In [2]:
def get_player_dataframe(df,w_l):
    stats_cols=[column for column in df.columns if w_l[0]+"_" in column]
    columns=['match_id',w_l+'_id','date']+stats_cols
    new_cols=['match_id','player_id','date']+[column[2:] for column in columns[3:]]
    new_df=df[columns]
    new_df.columns=new_cols
    new_df['label']=1 if w_l=='winner' else 0
    return new_df

In [3]:
df=pd.read_csv("stats_df.csv",index_col=0).reset_index(drop=True)
winner_df=get_player_dataframe(df,'winner')
loser_df=get_player_dataframe(df,'loser')
players_df=pd.concat([winner_df,loser_df]).sort_values(by='player_id').reset_index(drop=True)
groupby_df=players_df.groupby('player_id')
display(groupby_df.first())

,match_id,date,sf_rank,sf_elo,i_o_rank,i_o_elo_rank,ace,df,tt_p,sv_w,...,svp_game,r_ip_w,pwon_r_game,bp_game,r_game_w,gm_w,g_dominance,br_ratio,win_p,label
player_id,,,,,,,,,,,,,,,,,,,,,
284,85767,1992-04-06,11.0,2134.0,13.0,2089.0,0.046875,0.000000,0.438596,0.593750,...,0.700000,0.260870,1.333333,0.111111,0.000000,0.368421,0.000000,0.000000,0.174474,0
529,86485,1992-06-08,22.0,2011.0,72.0,1893.0,0.015873,0.015873,0.573643,0.666667,...,0.727273,0.542373,3.200000,1.000000,0.400000,0.571429,1.466667,0.400000,0.482737,1
536,81921,1991-04-08,91.0,1818.0,155.0,1779.0,0.022989,0.000000,0.497462,0.620690,...,0.769231,0.415094,3.142857,0.642857,0.142857,0.444444,0.619048,0.740741,0.321183,0
581,85109,1992-02-10,8.0,2154.0,7.0,2146.0,0.109756,0.036585,0.476821,0.621951,...,0.818182,0.396226,1.909091,0.272727,0.090909,0.454545,0.500000,1.000000,0.901187,0
587,80994,1991-01-07,120.0,1801.0,168.0,1764.0,0.016393,0.098361,0.454545,0.442623,...,0.400000,0.492537,3.666667,0.888889,0.333333,0.368421,0.555556,0.625000,0.832060,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45105,175550,2019-09-23,27.0,2043.0,41.0,1970.0,0.220588,0.044118,0.544828,0.705882,...,1.000000,0.455882,3.100000,0.900000,0.200000,0.619048,0.000000,0.000000,0.725686,1
45148,177250,2020-10-26,135.0,1757.0,96.0,1765.0,0.044776,0.014925,0.540741,0.731343,...,1.000000,0.380952,2.181818,0.181818,0.090909,0.545455,0.000000,0.000000,0.541638,1
45306,175073,2019-07-22,125.0,1705.0,197.0,1656.0,0.075758,0.015152,0.537313,0.530303,...,0.600000,0.569231,3.700000,0.600000,0.600000,0.600000,1.500000,1.250000,0.186388,1
45437,175542,2019-09-23,90.0,1851.0,89.0,1851.0,0.094340,0.094340,0.456897,0.641509,...,0.777778,0.358491,1.900000,0.100000,0.000000,0.368421,0.000000,0.000000,0.313700,0
50810,176512,2020-02-10,101.0,1839.0,65.0,1858.0,0.163265,0.020408,0.521053,0.714286,...,0.882353,0.353659,1.812500,0.125000,0.125000,0.515152,1.062500,3.500000,0.363923,1